using System.Reflection;
using System.Text.Json;
using Workspace.Application;

// Generate browser types from the same public contracts used by the HTTP endpoints.
var pending = new Queue<Type>(typeof(ConfigurationDto).Assembly.GetTypes().Where(x => x.IsPublic && (x.Name.EndsWith("Dto") || x.Name.EndsWith("Command"))));
var seen = new HashSet<Type>();
var declarations = new SortedDictionary<string, string>();
string TypeName(Type type)
{
    if (Nullable.GetUnderlyingType(type) is { } inner) return TypeName(inner) + " | null";
    if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTimeOffset)) return "string";
    if (type == typeof(bool)) return "boolean";
    if (type.IsPrimitive || type == typeof(decimal)) return "number";
    if (type == typeof(JsonElement)) return "JsonValue";
    if (type.IsArray) return $"({TypeName(type.GetElementType()!)})[]";
    if (type.IsGenericType) return $"({TypeName(type.GetGenericArguments()[0])})[]";
    pending.Enqueue(type); return type.Name;
}
var nullable = new NullabilityInfoContext();
while (pending.TryDequeue(out var type))
{
    if (!seen.Add(type)) continue;
    if (type.IsEnum) { declarations[type.Name] = $"export type {type.Name} = {string.Join(" | ", Enum.GetNames(type).Select(x => $"'{x}'"))}"; continue; }
    var properties = type.GetProperties(BindingFlags.Instance | BindingFlags.Public).Select(p =>
    {
        var name = JsonNamingPolicy.CamelCase.ConvertName(p.Name);
        var value = TypeName(p.PropertyType);
        if (!p.PropertyType.IsValueType && nullable.Create(p).ReadState == NullabilityState.Nullable) value += " | null";
        return $"  {name}: {value}";
    });
    declarations[type.Name] = $"export type {type.Name} = {{\n{string.Join("\n", properties)}\n}}";
}
var output = "// Generated by tools/Workspace.Contracts. Do not edit by hand.\nexport type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }\n\n" + string.Join("\n\n", declarations.Values) + "\n";
var path = Path.GetFullPath(args.Length > 0 ? args[0] : "src/Workspace.Client/src/contracts.generated.ts");
if (args.Contains("--check"))
{
    if (!File.Exists(path) || File.ReadAllText(path).Replace("\r\n", "\n") != output) throw new Exception("API 契約已變更，請重新產生前端型別。");
}
else File.WriteAllText(path, output);
