// Generated by tools/Workspace.Contracts. Do not edit by hand.
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }

export type AccountDto = {
  id: string
  displayName: string
  coordinationVersion: number
  cards: (CardDto)[]
}

export type AuditEventDto = {
  id: string
  occurredAt: string
  description: string
}

export type CardDto = {
  id: string
  accountId: string
  displayName: string
  usageStatus: CardUsageStatus
  primaryOperatorName: string | null
  reservation: ReservationDto | null
}

export type CardUsageCommand = {
  status: CardUsageStatus
  assignMeAsPrimaryOperator: boolean
}

export type CardUsageStatus = 'Available' | 'InUse' | 'NotInUse'

export type ChangeNicknameCommand = {
  nickname: string
}

export type CollaborationSettingsDto = {
  heartbeatSeconds: number
  reconcileSeconds: number
}

export type CollectionDefinition = {
  id: string
  name: string
  kind: CollectionKind
  version: number
}

export type CollectionKind = 'Cards' | 'Accounts' | 'Free'

export type CollectionSnapshotDto = {
  collection: CollectionDefinition
  records: (RecordDto)[]
  fields: (FieldDto)[]
  values: (ValueDto)[]
}

export type ConfigurationDto = {
  settings: WorkspaceSettings
  collections: (CollectionDefinition)[]
  views: (ViewDto)[]
  stages: (StageDefinition)[]
  regions: (NamedTargetDto)[]
}

export type CoordinationCommand = {
  cardId: string
  regionId: string
  expectedAccountVersion: number
}

export type CreateAccountCommand = {
  displayName: string
}

export type CreateCardCommand = {
  displayName: string
}

export type CreateCollectionCommand = {
  name: string
}

export type CurrentSessionDto = {
  participantId: string
  nickname: string
  canReadAudit: boolean
}

export type FieldBinding = 'None' | 'Resource'

export type FieldDto = {
  id: string
  collectionId: string
  name: string
  kind: FieldKind
  scope: FieldScope
  binding: FieldBinding
  options: (FieldOption)[]
  relationCollectionId: string | null
  color: string
  position: number
  required: boolean
  hidden: boolean
  version: number
}

export type FieldKind = 'Text' | 'Integer' | 'Number' | 'SingleSelect' | 'MultiSelect' | 'Checkbox' | 'Date' | 'DateTime' | 'Relation' | 'Marker'

export type FieldOption = {
  id: string
  name: string
  color: string
}

export type FieldScope = 'Individual' | 'Common' | 'Shared'

export type MoveStageCommand = {
  stageId: string
  expectedVersion: number
}

export type NamedTargetDto = {
  id: string
  name: string
  version: number
}

export type PresenceCommand = {
  collectionId: string | null
  recordId: string | null
  fieldId: string | null
  mode: string
}

export type PresenceMemberDto = {
  participantId: string
  nickname: string
  shortCode: string
  color: string
  targets: (PresenceTargetDto)[]
}

export type PresenceSnapshotDto = {
  epoch: string
  version: number
  members: (PresenceMemberDto)[]
}

export type PresenceTargetDto = {
  collectionId: string
  recordId: string | null
  fieldId: string | null
  mode: string
  label: string
}

export type RecordDto = {
  id: string
  name: string
  accountId: string | null
  stageId: string | null
  version: number
}

export type RegionDto = {
  id: string
  displayName: string
}

export type ReleaseCommand = {
  cardId: string
  expectedAccountVersion: number
  expectedReservationVersion: number
}

export type RenameCommand = {
  name: string
  expectedVersion: number
}

export type ReservationDto = {
  id: string
  regionId: string
  regionName: string
  state: ReservationState
  version: number
}

export type ReservationState = 'Reserved' | 'Occupied' | 'Released'

export type SaveFieldCommand = {
  collectionId: string
  name: string
  kind: FieldKind
  scope: FieldScope
  options: (FieldOption)[]
  relationCollectionId: string | null
  color: string
  position: number
  required: boolean
  hidden: boolean
  expectedVersion: number
}

export type SaveSettingsCommand = {
  name: string
  cardLabel: string
  settingsLabel: string
  expectedVersion: number
}

export type SaveValueCommand = {
  value: JsonValue
  expectedVersion: number
  expectedDefinitionVersion: number
  attached: boolean
}

export type SaveViewCommand = {
  collectionId: string
  name: string
  display: string
  position: number
  stageId: string | null
  hiddenFields: (string)[]
  sortFieldId: string | null
  descending: boolean
  filterFieldId: string | null
  filterText: string
  expectedVersion: number
}

export type StageDefinition = {
  id: string
  name: string
  position: number
  version: number
}

export type ValueDto = {
  fieldId: string
  recordId: string | null
  value: JsonValue
  attached: boolean
  version: number
}

export type VersionCommand = {
  expectedVersion: number
}

export type ViewDto = {
  id: string
  collectionId: string
  name: string
  display: string
  position: number
  stageId: string | null
  hiddenFields: (string)[]
  sortFieldId: string | null
  descending: boolean
  filterFieldId: string | null
  filterText: string
  version: number
}

export type WorkspaceSettings = {
  id: number
  name: string
  cardLabel: string
  settingsLabel: string
  version: number
}

export type WorkspaceSnapshotDto = {
  version: number
  regions: (RegionDto)[]
  accounts: (AccountDto)[]
}

export type WorkspaceVersionDto = {
  version: number
}
