// Generated by tools/Workspace.Contracts. Do not edit by hand.
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }

export type AccountDto = {
  id: string
  displayName: string
  coordinationVersion: number
  cards: (CardDto)[]
}

export type ActivityDto = {
  id: string
  qualificationCycleId: string
  channel: string
  occurredAt: string
  recordedAt: string
  endedAt: string | null
  operatorName: string | null
  version: number
}

export type AuditEventDto = {
  id: string
  occurredAt: string
  description: string
}

export type CardDto = {
  id: string
  accountId: string
  displayName: string
  usageStatus: CardUsageStatus
  primaryOperatorName: string | null
  reservation: ReservationDto | null
}

export type CardProgressionDto = {
  cardId: string
  name: string
  accountId: string
  stageId: string | null
  replacesCardId: string | null
  archivedAt: string | null
  profileId: string | null
  level: number
  taskItems: number
  meritBalance: number
  cumulativeCredits: number
  version: number
  creditVersion: number
  permanentlyDisqualified: boolean
  qualificationStatus: string
  cycles: (QualificationDto)[]
  activities: (ActivityDto)[]
  entries: (CreditEntryDto)[]
}

export type CardUsageCommand = {
  status: CardUsageStatus
  assignMeAsPrimaryOperator: boolean
}

export type CardUsageStatus = 'Available' | 'InUse' | 'NotInUse'

export type ChangeNicknameCommand = {
  nickname: string
}

export type CollaborationSettingsDto = {
  heartbeatSeconds: number
  reconcileSeconds: number
}

export type CollectionDefinition = {
  id: string
  name: string
  kind: CollectionKind
  version: number
}

export type CollectionKind = 'Cards' | 'Accounts' | 'Free'

export type CollectionSnapshotDto = {
  collection: CollectionDefinition
  records: (RecordDto)[]
  fields: (FieldDto)[]
  values: (ValueDto)[]
}

export type ConfigurationDto = {
  settings: WorkspaceSettings
  collections: (CollectionDefinition)[]
  views: (ViewDto)[]
  stages: (StageDefinition)[]
  regions: (NamedTargetDto)[]
}

export type CoordinationCommand = {
  cardId: string
  regionId: string
  expectedAccountVersion: number
}

export type CreateAccountCommand = {
  displayName: string
}

export type CreateCardCommand = {
  displayName: string
}

export type CreateCollectionCommand = {
  name: string
}

export type CreditEntryDto = {
  id: string
  kind: CreditKind
  amount: number
  totalAfter: number
  reason: string
  recordedAt: string
}

export type CreditKind = 'Income' | 'Conversion' | 'Correction'

export type CurrentSessionDto = {
  participantId: string
  nickname: string
  canReadAudit: boolean
}

export type FieldBinding = 'None' | 'Resource'

export type FieldDto = {
  id: string
  collectionId: string
  name: string
  kind: FieldKind
  scope: FieldScope
  binding: FieldBinding
  options: (FieldOption)[]
  relationCollectionId: string | null
  color: string
  position: number
  required: boolean
  hidden: boolean
  version: number
}

export type FieldKind = 'Text' | 'Integer' | 'Number' | 'SingleSelect' | 'MultiSelect' | 'Checkbox' | 'Date' | 'DateTime' | 'Relation' | 'Marker'

export type FieldOption = {
  id: string
  name: string
  color: string
}

export type FieldScope = 'Individual' | 'Common' | 'Shared'

export type MoveStageCommand = {
  stageId: string
  expectedVersion: number
}

export type NamedTargetDto = {
  id: string
  name: string
  version: number
}

export type PresenceCommand = {
  collectionId: string | null
  recordId: string | null
  fieldId: string | null
  mode: string
}

export type PresenceMemberDto = {
  participantId: string
  nickname: string
  shortCode: string
  color: string
  targets: (PresenceTargetDto)[]
}

export type PresenceSnapshotDto = {
  epoch: string
  version: number
  members: (PresenceMemberDto)[]
}

export type PresenceTargetDto = {
  collectionId: string
  recordId: string | null
  fieldId: string | null
  mode: string
  label: string
}

export type ProgressionCommand = {
  requestId: string
  operation: ProgressionOperation
  expectedVersion: number
  profileId: string | null
  level: number
  taskItems: number
  meritBalance: number
  amount: number
  expectedCreditVersion: number
  activityId: string | null
  expectedActivityVersion: number
  channel: string
  occurredAt: string | null
  reason: string
  replacementName: string
}

export type ProgressionOperation = 'ReportProgress' | 'StartActivity' | 'CorrectActivity' | 'EndActivity' | 'Requalify' | 'Disqualify' | 'InvalidateQualification' | 'RecordIncome' | 'RecordConversion' | 'CorrectCredits' | 'Archive' | 'CreateReplacement'

export type ProgressionProfile = {
  id: string
  name: string
  levelTarget: number
  taskItemTarget: number
  meritTarget: number
  version: number
}

export type ProgressionResultDto = {
  requestId: string
  workspaceVersion: number
  cardVersion: number
  creditVersion: number
  meritBalance: number
  cumulativeCredits: number
  activityId: string | null
  replacementCardId: string | null
}

export type ProgressionSettings = {
  id: number
  timeZoneId: string
  resetHour: number
  conversionRequiresActiveActivity: boolean
  accumulationStageId: string
  version: number
}

export type ProgressionSnapshotDto = {
  version: number
  serverTime: string
  settings: ProgressionSettings
  profiles: (ProgressionProfile)[]
  stages: (StageDefinition)[]
  cards: (CardProgressionDto)[]
}

export type QualificationDto = {
  id: string
  qualifiedAt: string
  eligibleFrom: string
  timeZoneId: string
  resetHour: number
  thresholdSnapshot: ProgressionProfile
  activatedAt: string | null
  invalidatedAt: string | null
  invalidationReason: string
}

export type RecordDto = {
  id: string
  name: string
  accountId: string | null
  stageId: string | null
  version: number
}

export type RegionDto = {
  id: string
  displayName: string
}

export type ReleaseCommand = {
  cardId: string
  expectedAccountVersion: number
  expectedReservationVersion: number
}

export type RenameCommand = {
  name: string
  expectedVersion: number
}

export type ReservationDto = {
  id: string
  regionId: string
  regionName: string
  state: ReservationState
  version: number
}

export type ReservationState = 'Reserved' | 'Occupied' | 'Released'

export type SaveFieldCommand = {
  collectionId: string
  name: string
  kind: FieldKind
  scope: FieldScope
  options: (FieldOption)[]
  relationCollectionId: string | null
  color: string
  position: number
  required: boolean
  hidden: boolean
  expectedVersion: number
}

export type SaveProfileCommand = {
  name: string
  levelTarget: number
  taskItemTarget: number
  meritTarget: number
  expectedVersion: number
}

export type SaveProgressionSettingsCommand = {
  timeZoneId: string
  conversionRequiresActiveActivity: boolean
  accumulationStageId: string
  expectedVersion: number
}

export type SaveSettingsCommand = {
  name: string
  cardLabel: string
  settingsLabel: string
  expectedVersion: number
}

export type SaveTransitionCommand = {
  requirement: StageRequirement
  allowedFromStageIds: (string)[]
  expectedVersion: number
}

export type SaveValueCommand = {
  value: JsonValue
  expectedVersion: number
  expectedDefinitionVersion: number
  attached: boolean
}

export type SaveViewCommand = {
  collectionId: string
  name: string
  display: string
  position: number
  stageId: string | null
  hiddenFields: (string)[]
  sortFieldId: string | null
  descending: boolean
  filterFieldId: string | null
  filterText: string
  expectedVersion: number
}

export type StageDefinition = {
  id: string
  name: string
  position: number
  version: number
  entryRequirement: StageRequirement
  allowedFromStageIdsJson: string
}

export type StageRequirement = 'None' | 'Level' | 'Task' | 'Qualification'

export type ValueDto = {
  fieldId: string
  recordId: string | null
  value: JsonValue
  attached: boolean
  version: number
}

export type VersionCommand = {
  expectedVersion: number
}

export type ViewDto = {
  id: string
  collectionId: string
  name: string
  display: string
  position: number
  stageId: string | null
  hiddenFields: (string)[]
  sortFieldId: string | null
  descending: boolean
  filterFieldId: string | null
  filterText: string
  version: number
}

export type WorkspaceSettings = {
  id: number
  name: string
  cardLabel: string
  settingsLabel: string
  version: number
}

export type WorkspaceSnapshotDto = {
  version: number
  regions: (RegionDto)[]
  accounts: (AccountDto)[]
}

export type WorkspaceVersionDto = {
  version: number
}
