using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workspace.Infrastructure.Persistence.Migrations;

[DbContext(typeof(WorkspaceDbContext))]
[Migration("202609100001_CoreCoordination")]
public sealed partial class CoreCoordination : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<long>(name: "CoordinationVersion", table: "preview_accounts", type: "bigint", nullable: false, defaultValue: 0L);
        migrationBuilder.Sql("""
            CREATE TABLE workspace_state ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Version" bigint NOT NULL);
            CREATE TABLE participant_sessions ("Id" uuid PRIMARY KEY, "SessionToken" uuid NOT NULL UNIQUE, "Nickname" varchar(80) NOT NULL, "CreatedAt" timestamptz NOT NULL);
            CREATE TABLE field_regions ("Id" uuid PRIMARY KEY, "DisplayName" varchar(80) NOT NULL);
            CREATE TABLE character_cards ("Id" uuid PRIMARY KEY, "AccountId" uuid NOT NULL REFERENCES preview_accounts("Id") ON DELETE RESTRICT, "DisplayName" varchar(80) NOT NULL, "UsageStatus" text NOT NULL, "PrimaryOperatorId" uuid NULL);
            CREATE TABLE resource_reservations ("Id" uuid PRIMARY KEY, "AccountId" uuid NOT NULL REFERENCES preview_accounts("Id") ON DELETE RESTRICT, "CardId" uuid NOT NULL REFERENCES character_cards("Id") ON DELETE RESTRICT, "RegionId" uuid NOT NULL REFERENCES field_regions("Id") ON DELETE RESTRICT, "State" text NOT NULL, "CreatedByParticipantId" uuid NOT NULL, "UpdatedAt" timestamptz NOT NULL, "Version" bigint NOT NULL);
            CREATE INDEX "IX_resource_reservations_AccountId_State" ON resource_reservations ("AccountId", "State");
            CREATE UNIQUE INDEX "IX_resource_reservations_CardId" ON resource_reservations ("CardId") WHERE "State" <> 'Released';
            CREATE TABLE audit_events ("Id" uuid PRIMARY KEY, "ActorParticipantId" uuid NOT NULL, "ActorNameSnapshot" varchar(80) NOT NULL, "Description" varchar(500) NOT NULL, "OccurredAt" timestamptz NOT NULL);
            INSERT INTO workspace_state ("Id", "Version") VALUES (1, 0);
            INSERT INTO field_regions ("Id", "DisplayName") VALUES
              ('20000000-0000-0000-0000-000000000001', '迷霧森林'),
              ('20000000-0000-0000-0000-000000000002', '赤色峽谷');
            INSERT INTO character_cards ("Id", "AccountId", "DisplayName", "UsageStatus", "PrimaryOperatorId") VALUES
              ('30000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001', '青鳥一號', 'Available', NULL),
              ('30000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000001', '青鳥二號', 'Available', NULL),
              ('30000000-0000-0000-0000-000000000003', '10000000-0000-0000-0000-000000000002', '山貓一號', 'Available', NULL);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE audit_events, resource_reservations, character_cards, field_regions, participant_sessions, workspace_state;");
        migrationBuilder.DropColumn(name: "CoordinationVersion", table: "preview_accounts");
    }
}
